# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25b73cbfa4e85fb5e1c80a51bd0ea9d10bbc4857032209e97dbf41686ef58f18b5b40a668f0a329811e6e230a9b318899949e99ee045a272eb4df5f7e301e2e8

test:
  secret_key_base: 265cbc68d02cb512c486075fce65c3f845f73260b4b90c41b237351e55c45a1986ece71d7bb2bc0e294cf7963b20e37b55ee01ae2e9863bb9d1deecf24e8db4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
